const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  sendMessage: (msg) => ipcRenderer.send('send-message', msg),
  selectImageFile: () => ipcRenderer.invoke("select-image-file"),
  getImageFolder: () => ipcRenderer.invoke("get-image-folder"),
  isFileExist: (file) => ipcRenderer.invoke("is-file-exist", file),
  getVersion: () => ipcRenderer.invoke("get-version"),
  exportStory : () =>ipcRenderer.invoke("export-story"),
  importStory : () =>ipcRenderer.invoke("import-story"),
  
  // page storys
  getReadyStorys: () => ipcRenderer.invoke("get-ready-storys"),
  getIdStory: () => ipcRenderer.invoke("get-id-story"),
  getStory: () => ipcRenderer.invoke("get-story"),
  getTexteffects: () => ipcRenderer.invoke("get-texteffects"),
  getChapters: () => ipcRenderer.invoke("get-chapters"),
  getChapter: () => ipcRenderer.invoke("get-chapter"),
  getIdChapter: () => ipcRenderer.invoke("get-id-chapter"),
  getButtons: () => ipcRenderer.invoke("get-buttons"),
  getObjects: () => ipcRenderer.invoke("get-objects"),
  
  // page création d'histoire
  updateImageChapter: (value) =>ipcRenderer.invoke("update-image-chapter", value),
  getAllStorys: () => ipcRenderer.invoke("get-all-storys"),
  createStory: (value) => ipcRenderer.invoke("create-story", value),
  updateStory: (value) => ipcRenderer.invoke("update-story", value),
  updateLifeStory: (value) => ipcRenderer.invoke("update-life-story", value),
  updateModeStory: (value) => ipcRenderer.invoke("update-mode-story", value),
  updateStoryName: (value) => ipcRenderer.invoke("update-story-name", value),
  updateStoryReady: (value) => ipcRenderer.invoke("update-story-ready", value),
  deleteStory: (value) => ipcRenderer.invoke("delete-story", value),
  createObject: () => ipcRenderer.invoke("create-object"),
  createTexteffect: () => ipcRenderer.invoke("create-texteffect"),
  updateTexteTexteffect: (value) => ipcRenderer.invoke("update-texte-texteffect", value),
  updatePositiveTexteffect: (value) => ipcRenderer.invoke("update-positive-texteffect", value),
  updateObjectTexteffect: (value) => ipcRenderer.invoke("update-object-texteffect", value),
  deleteTexteffect: (value) => ipcRenderer.invoke("delete-texteffect", value),
  createChapter: () => ipcRenderer.invoke("create-chapter"),
  updateChapter: (value) => ipcRenderer.invoke("update-chapter", value),
  updateObjectName: (value) => ipcRenderer.invoke("update-object-name", value),
  updateObjectDescription: (value) => ipcRenderer.invoke("update-object-description", value),
  updateObjectType: (value) => ipcRenderer.invoke("update-object-type", value),
  updateChapterName: (value) => ipcRenderer.invoke("update-chapter-name", value),
  updateChapterTexte: (value) => ipcRenderer.invoke("update-chapter-texte", value),
  deleteChapter: (value) => ipcRenderer.invoke("delete-chapter", value),
  deleteObject: (value) => ipcRenderer.invoke("delete-object", value),
  createButton: (value) => ipcRenderer.invoke("create-button", value),
  updateButton: (value) => ipcRenderer.invoke("update-button", value),
  updateButtonName: (value) => ipcRenderer.invoke("update-button-name", value),
  updateButtonType: (value) => ipcRenderer.invoke("update-button-type", value),
  updateButtonLostLife: (value) => ipcRenderer.invoke("update-button-lostlife", value),
  updateButtonRequireObject: (value) => ipcRenderer.invoke("update-button-requireobject", value),
  updateButtonGiveObject: (value) => ipcRenderer.invoke("update-button-giveobject", value),
  updateButtonNextChapter: (value) => ipcRenderer.invoke("update-button-next-chapter", value),
  deleteButton: (value) => ipcRenderer.invoke("delete-button", value),

  // navigation
  navGlobal: (value) => ipcRenderer.invoke("nav-global", value),
  reloadPage: (callback) => ipcRenderer.on("reload-page", (event, data) => callback(data)),
  getPage: () => ipcRenderer.invoke("get-page"),
  
  // options
  open1Screen: () => ipcRenderer.send("open-1-screen"),
  open2Screens: () => ipcRenderer.send("open-2-screens"),
  openMobileScreenQrcode: () => ipcRenderer.send("open-mobile-screen-qrcode"),
  getQrcodeMobile: () => ipcRenderer.invoke("get-qrcode-mobile"),
  setVolume: (value) => ipcRenderer.invoke("set-volume", value),
  getVolume: () => ipcRenderer.invoke("get-volume"),
  setFullscreen: (value) => ipcRenderer.invoke("set-fullscreen", value),
  getFullscreen: () => ipcRenderer.invoke("get-fullscreen"),
  getModeScreen: () => ipcRenderer.invoke("get-mode-screen"),
  setWifiName: (value) => ipcRenderer.invoke("set-wifi-name", value),
  getWifiName: () => ipcRenderer.invoke("get-wifi-name"),
  quitApp: () => ipcRenderer.invoke("quit-app"),
});
